// <auto-generated />

using System.Collections.Generic;
using Newtonsoft.Json;

namespace DialogueController.Client
{

    public partial class RunDialogueObject
    {
        [JsonProperty("line", NullValueHandling = NullValueHandling.Ignore)]
        public string Line { get; set; }

        [JsonProperty("forceRadio", NullValueHandling = NullValueHandling.Ignore)]
        public bool? ForceRadio { get; set; }

        [JsonProperty("phoneCall", NullValueHandling = NullValueHandling.Ignore)]
        public bool? PhoneCall { get; set; }

        [JsonProperty("speakers", NullValueHandling = NullValueHandling.Ignore)]
        public Dictionary<string, string> Speakers { get; set; }

        [JsonProperty("forcePedsVisible", NullValueHandling = NullValueHandling.Ignore)]
        public bool? ForcePedsVisible { get; set; }

        [JsonProperty("gxt", NullValueHandling = NullValueHandling.Ignore)]
        public string Gxt { get; set; }

        [JsonProperty("peds", NullValueHandling = NullValueHandling.Ignore)]
        public Dictionary<string, int> Peds { get; set; }
    }

    public partial class RunDialogueObject
    {
        public static RunDialogueObject FromJson(string json) => JsonConvert.DeserializeObject<RunDialogueObject>(json, DialogueController.Client.Converter.Settings);
    }
}
